# Generated by Django 5.2.5 on 2025-08-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
    ]
